# Development
name = "w3-api-gateway-local"
account_id = "fffa4b4363a7e5250af8357087263b3a"
main = "./dist/worker.js"

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2022-09-28"
compatibility_flags = ["url_standard"]

# We need to let wrangler bundle while D1 is in Beta
no_bundle = false

[vars]
ENV = "local"
DEBUG = "true"
DID = "did:web:local.web3.storage"

[build]
command = "scripts/cli.js build"
watch_dir = "src"

[miniflare]
d1_persist = ".wrangler/miniflare"
