# Development
name = "w3-api-gateway-local"
type = "javascript"
main = "./dist/worker.js"
account_id = "fffa4b4363a7e5250af8357087263b3a"
compatibility_date = "2022-09-28"
compatibility_flags = ["url_standard"]
workers_dev = true

[build]
command = "scripts/cli.js build"
watch_dir = "src"

[vars]
ENV = "local"
DEBUG = "true"
DID = "did:web:local.web3.storage"
