name: '@web3-storage/api-gateway PR'
on:
  pull_request:
    paths:
      - 'packages/api-gateway/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: install dependencies
        run: |
          pnpm --filter '@web3-storage/api-gateway' install
      - name: set env.wrangler_name
        run: |
          wrangler_name="w3-api-gateway-$( echo "$GITHUB_REF" | md5 )"
          echo "wrangler_name=$wrangler_name" >> $GITHUB_ENV
      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'packages/api-gateway'
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: publish --name=${{ env.wrangler_name }}
